/**
 * Download helpers for Meta-Prompt Engine outputs.
 * Supports: Markdown (.md), HTML (.html), PDF (print dialog).
 * All downloads include attribution footer: FinPrompt URL + Kalilur Rahman.
 */

// ─────────────────────────────────────────────
// Attribution Footer Content
// ─────────────────────────────────────────────

const FINPROMPT_URL = "https://kr-finance-prompt-hub.lovable.app/library";
const KALILUR_URL = "https://kalilurrahman.lovable.app";
const ENGINE_URL = "https://kr-finance-prompt-hub.lovable.app/engine";

function timestamp(): string {
  return new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
}

function footerMD(): string {
  return [
    "",
    "---",
    "",
    `📚 **Source:** [FinPrompt Library](${FINPROMPT_URL}) — Curated finance prompts for AI platforms`,
    `✍️ **Curated by** [Kalilur Rahman](${KALILUR_URL})`,
    `🤖 **Generated by** [Meta-Prompt Engine v1.0](${ENGINE_URL})`,
    `🕐 **Generated:** ${timestamp()}`,
    "",
  ].join("\n");
}

function footerHTML(): string {
  return `
  <footer>
    <hr style="margin: 32px 0 18px; border: none; border-top: 1px solid #ddd;">
    <p>📚 <strong>Source:</strong> <a href="${FINPROMPT_URL}">FinPrompt Library</a> — curated finance prompts for AI platforms</p>
    <p>✍️ <strong>Curated by</strong> <a href="${KALILUR_URL}">Kalilur Rahman</a></p>
    <p>🤖 <strong>Generated by</strong> <a href="${ENGINE_URL}">Meta-Prompt Engine v1.0</a></p>
    <p class="meta">🕐 Generated: ${timestamp()}</p>
  </footer>`;
}

// ─────────────────────────────────────────────
// Shared Utilities
// ─────────────────────────────────────────────

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

function safeFilename(title: string): string {
  return title
    .replace(/[^a-z0-9\s]/gi, "")
    .replace(/\s+/g, "-")
    .toLowerCase()
    .slice(0, 50)
    .replace(/-+$/, "");
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ─────────────────────────────────────────────
// Markdown Download
// ─────────────────────────────────────────────

export function downloadMarkdown(content: string, title: string): void {
  const md = `# ${title}\n\n${content}\n${footerMD()}`;
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  triggerDownload(blob, `${safeFilename(title) || "finprompt"}.md`);
}

// ─────────────────────────────────────────────
// Shared styled HTML document builder
// ─────────────────────────────────────────────

function buildHtmlDoc(content: string, title: string, forPrint = false): string {
  const escaped = escapeHtml(content);
  const printExtra = forPrint
    ? `@page { margin: 18mm 16mm; } @media print { .no-print { display: none; } }`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} | FinPrompt</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Segoe UI', Inter, 'Helvetica Neue', Arial, sans-serif;
      background: #f7f5f2;
      color: #1a1a2e;
      min-height: 100vh;
      font-size: 14px;
      line-height: 1.65;
    }
    .page {
      max-width: 820px;
      margin: 0 auto;
      padding: 40px 28px 60px;
      background: #fff;
      min-height: 100vh;
      box-shadow: 0 0 40px rgba(0,0,0,0.06);
    }
    header {
      border-bottom: 3px solid #b8860b;
      padding-bottom: 20px;
      margin-bottom: 32px;
    }
    .badge {
      display: inline-block;
      background: #b8860b;
      color: #fff;
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      padding: 3px 10px;
      border-radius: 4px;
      margin-bottom: 10px;
      font-family: 'Courier New', monospace;
    }
    h1 {
      font-size: 1.55rem;
      font-weight: 700;
      color: #111;
      line-height: 1.3;
    }
    .prompt-box {
      background: #f8f6f2;
      border: 1px solid #e6dfc8;
      border-left: 5px solid #b8860b;
      border-radius: 8px;
      padding: 24px 28px;
      margin: 8px 0 24px;
    }
    .prompt-box pre {
      font-family: 'Courier New', 'Consolas', 'Lucida Console', monospace;
      font-size: 13px;
      line-height: 1.85;
      white-space: pre-wrap;
      word-break: break-word;
      color: #1e1e1e;
    }
    footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e0d8c8;
      font-size: 12.5px;
      color: #666;
    }
    footer p {
      margin: 5px 0;
    }
    footer a {
      color: #b8860b;
      text-decoration: none;
      font-weight: 600;
    }
    footer a:hover {
      text-decoration: underline;
    }
    .meta {
      margin-top: 12px !important;
      font-size: 11px;
      color: #999;
    }
    ${printExtra}
  </style>
</head>
<body>
  <div class="page">
    <header>
      <div class="badge">FinPrompt · Meta-Prompt Engine</div>
      <h1>${escapeHtml(title)}</h1>
    </header>

    <div class="prompt-box">
      <pre>${escaped}</pre>
    </div>

    ${footerHTML()}
  </div>
</body>
</html>`;
}

// ─────────────────────────────────────────────
// HTML Download
// ─────────────────────────────────────────────

export function downloadHTML(content: string, title: string): void {
  const html = buildHtmlDoc(content, title, false);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  triggerDownload(blob, `${safeFilename(title) || "finprompt"}.html`);
}

// ─────────────────────────────────────────────
// PDF (Print Dialog)
// ─────────────────────────────────────────────

export function downloadPDF(content: string, title: string): void {
  const html = buildHtmlDoc(content, title, true);

  const win = window.open("", "_blank", "width=900,height=700,scrollbars=yes");
  if (!win) {
    // Popup blocked — fallback to HTML download
    downloadHTML(content, title);
    return;
  }

  win.document.open();
  win.document.write(html);
  win.document.close();

  // Wait for fonts/layout to render before printing
  setTimeout(() => {
    win.focus();
    win.print();
    // Close print window after a delay
    setTimeout(() => {
      try { win.close(); } catch { /* ignore */ }
    }, 1200);
  }, 600);
}
